// ===== Interfeys tili: UZ / RU / EN. Statik matnlar (menyu, sarlavhalar, tugmalar, yorliqlar) tarjima qilinadi;
// formulalar, jarayon xabarlari (AI xabarlari, Review matni) o'zbek tilida qoladi. =====
const I18N={
ru:{
'☰ Boshqaruv':'☰ Управление','Quritgich aparat AI — erta ogohlantirish va hodisa tahlili':'Quritgich aparat AI — раннее предупреждение и анализ инцидентов',
'Normal ish':'Нормальная работа','Nam material namligi keskin oshdi':'Резкий рост влажности исходного материала','Birlamchi havo yetishmovchiligi (1-1 klapan / ventilyator)':'Недостаток первичного воздуха (клапан 1-1 / вентилятор)','Gaz klapani 1-2 zich yopilmayapti (gaz oshib ketdi)':'Газовый клапан 1-2 не закрывается плотно (избыток газа)','TT02 harorat datchigi siljishi (past ko‘rsatmoqda)':'Дрейф датчика температуры TT02 (занижает)','Nam material kelishi to‘xtadi (konveyer 1)':'Прекратилась подача влажного материала (конвейер 1)','Shnekli ta’minlagich 3 tiqilib qoldi':'Заклинил шнековый питатель 3','Bunker aralashtirgichi M02 to‘xtadi — material osilib qoldi':'Остановилась мешалка бункера M02 — материал завис',
'Erta ogohlantirish':'Раннее предупреждение','Nam materialni quritish qurilmasi':'Установка сушки влажного материала','Simulyatsiya · 4 soat · 10 s':'Симуляция · 4 ч · 10 с','Simulyatsiya · Real-time':'Симуляция · Реальное время',
'Umumiy ko‘rinish':'Обзор','Mnemosxema':'Мнемосхема','3D ko‘rinish':'3D-вид','Trendlar':'Тренды','AI xabarlari va indeks':'Сообщения ИИ и индекс','Hodisa tahlili (Review)':'Анализ инцидента (Review)','Hodisalar jurnali':'Журнал событий','Ommaviy sinov':'Массовое тестирование','O‘z ma’lumotingiz':'Ваши данные','Matematik model':'Математическая модель','Sozlamalar':'Настройки',
'Quritish qurilmasi ›':'Сушильная установка ›','↻ Yangilash':'↻ Обновить','Holat turi':'Тип ситуации','Variant':'Вариант','▶ Ishga tushirish':'▶ Запустить','To‘liq ko‘rsatish':'Показать полностью','Tezlik':'Скорость',
'Hodisagacha berilgan ogohlantirishlar, qurilma mnemosxemasi, AI xabarlari va xavf indeksi tarkibi.':'Предупреждения до инцидента, мнемосхема установки, сообщения ИИ и состав индекса риска.',
'AI indeksi ogohlantirishi (hodisadan oldin)':'Предупреждение индекса ИИ (до инцидента)','Mavjud PLC alarmlari (hodisadan oldin)':'Существующие аварии ПЛК (до инцидента)','AI diagnostika xabari (hodisadan oldin)':'Диагностика ИИ (до инцидента)','Birgalikda: eng erta ogohlantirish':'Вместе: самое раннее предупреждение',
'Nam materialni quritish qurilmasining texnologik va avtomatlashtirish sxemasi (chizma asosida). Qiymatlar real vaqtda yangilanadi: bunker sathi, shnek, gorelka alangasi, klapanlar holati va material oqimi.':'Технологическая схема и схема автоматизации установки сушки влажного материала. Значения обновляются в реальном времени: уровень бункера, шнек, пламя горелки, положение клапанов и поток материала.',
'Quritish qurilmasining uch o‘lchamli ko‘rinishi — mnemosxema bilan bir xil ma’lumotlardan olinadi (gorelka, quritish barabani, bunker, konveyerlar, siklon, filtr, mo‘ri, PLC va AI xavf indeksi). Sichqoncha bilan aylantiring, g‘ildirak bilan yaqinlashtiring, uskunani bosib ma’lumot ko‘ring. Pastdagi o‘ynatish tugmasi bilan jarayonni yurgizing.':'Трёхмерный вид сушильной установки — данные те же, что и на мнемосхеме (горелка, сушильный барабан, бункер, конвейеры, циклон, фильтр, труба, ПЛК и индекс риска ИИ). Вращайте мышью, приближайте колесом, нажимайте на оборудование для сведений.',
'Umumiy':'Общий','Konveyer':'Конвейер','Bunker':'Бункер','O‘txona':'Топка','Baraban':'Барабан','Siklon / filtr / mo‘ri':'Циклон / фильтр / труба','Mahsulot':'Продукт','PLC xonasi':'Комната ПЛК','Yuqoridan':'Сверху','Aylanish':'Вращение','⏪ Takror':'⏪ Повтор','🎓 Mashq':'🎓 Тренинг','🔇 Ovoz':'🔇 Звук','📄 PDF hisobot':'📄 PDF-отчёт',
'Bu qurilmada 3D (WebGL) ishlamadi. Mnemosxema bo‘limidan foydalaning.':'3D (WebGL) на этом устройстве не работает. Используйте раздел «Мнемосхема».',
'Haroratlar, havo/gaz nisbati, namlik, bunker sathi va dinamik xavf indeksi.':'Температуры, соотношение воздух/газ, влажность, уровень бункера и динамический индекс риска.',
'Haqiqiy qiymatlarni ham ko‘rsatish (faqat simulyatsiya)':'Показать также истинные значения (только симуляция)',
'TT01 — o‘txona harorati, °C':'TT01 — температура топки, °C','TT02 — quritish agenti harorati, °C (nuqtali chiziqlar — modeldan kutilgan qiymat ±2σ; uzuq chiziq — haqiqiy qiymat)':'TT02 — температура сушильного агента, °C (пунктир-точки — ожидаемое по модели ±2σ; штриховая — истинное значение)',
'λ — birlamchi havo / gaz nisbati (FT02 / 9,5·FT01)':'λ — отношение первичный воздух / газ (FT02 / 9,5·FT01)','Namlik, %: AT02 mahsulot (qora), AT01 kirish (kulrang), AI bashorati (sariq uzuq)':'Влажность, %: AT02 продукт (чёрная), AT01 вход (серая), прогноз ИИ (жёлтая штриховая)','LT01 — bunker sathi, %':'LT01 — уровень бункера, %','Dinamik xavf indeksi R(t)':'Динамический индекс риска R(t)','Excel’ga yuklab olish (.xlsx)':'Скачать в Excel (.xlsx)',
'AI xabarlari va xavf indeksi':'Сообщения ИИ и индекс риска','Operatorga beriladigan xabarlar, qurilma holati va indeks tashkil etuvchilari.':'Сообщения оператору, состояние установки и составляющие индекса.','AI xabarlari':'Сообщения ИИ',
'Kritik':'Критично','Ogohlantirish':'Предупреждение','Diagnostika':'Диагностика','Holat':'Состояние','Ma’lumot':'Информация',
'Tanlangan holat bo‘yicha avtomatik tahlil: sabab, voqealar ketma-ketligi, parametrlar o‘zgarishi, texnolog va KIP xulosasi.':'Автоматический анализ выбранной ситуации: причина, последовательность событий, изменение параметров, заключение технолога и КИПиА.','PDF hisobot (chop etish)':'PDF-отчёт (печать)',
'Tanlangan holat bo‘yicha PLC, AI va tizim voqealari vaqt tartibida. Operator har bir voqeani tasdiqlaydi (ACK).':'События ПЛК, ИИ и системы по выбранной ситуации в хронологическом порядке. Оператор подтверждает каждое событие (ACK).',
'Hammasini tasdiqlash':'Подтвердить все','CSV’ga eksport':'Экспорт в CSV','Tasdiqlarni tozalash':'Сбросить подтверждения','Voqealar':'События','tasdiqlanmagan':'не подтверждено','Hozircha voqea yo‘q.':'Событий пока нет.','Vaqt, min':'Время, мин','Daraja':'Уровень','Manba':'Источник','Voqea':'Событие','Tasdiqlash':'Подтвердить','Tasdiqlandi':'Подтверждено','Simulyatsiya':'Симуляция','Zaxira himoya':'Резервная защита',
'Har bir nosozlik turidan 10 tadan va 50 ta normal ish ssenariysi (joriy sozlamalar bilan).':'По 10 сценариев каждого типа неисправности и 50 сценариев нормальной работы (с текущими настройками).','Barcha ssenariylar bo‘yicha sinash':'Проверить по всем сценариям','5 ta variant bo‘yicha o‘rtacha':'Среднее по 5 вариантам',
'PLC/SCADA trendini Excel (.xlsx) yoki CSV fayldan yuklang. Fayl brauzerdan tashqariga chiqmaydi.':'Загрузите тренд ПЛК/SCADA из файла Excel (.xlsx) или CSV. Файл не покидает браузер.','Majburiy ustunlar:':'Обязательные столбцы:','. Ixtiyoriy:':'. Необязательные:','(klapanlar, %),':'(клапаны, %),','(tezlik, %) — ular bo‘lmasa tegishli izchillik tekshiruvlari o‘chiriladi.':'(скорость, %) — без них соответствующие проверки согласованности отключаются.',
'Diskretlik, soniya':'Дискретность, с','Normal deb olinadigan boshlang‘ich qism, %':'Начальная часть, принимаемая за норму, %','Fayl (.xlsx, .csv)':'Файл (.xlsx, .csv)','Namuna Excel yuklab olish':'Скачать образец Excel','Simulyatsiyaga qaytish':'Вернуться к симуляции',
'Vaqt — daqiqa, oqim — m³/soat (gaz, havo) va t/soat (material), harorat — °C, namlik — %.':'Время — минуты, расход — м³/ч (газ, воздух) и т/ч (материал), температура — °C, влажность — %.','1. Gorelka va o‘txona':'1. Горелка и топка','2. Quritish agenti (aralashma)':'2. Сушильный агент (смесь)','3. Quritish va mahsulot namligi':'3. Сушка и влажность продукта','4. Bunker va ta’minot':'4. Бункер и подача','5. Boshqaruv va himoya (PLC)':'5. Управление и защита (ПЛК)','6. AI: izchillik qoldiqlari':'6. ИИ: невязки согласованности','7. Dinamik xavf indeksi':'7. Динамический индекс риска','8. Taxminiy parametrlar':'8. Ориентировочные параметры',
'Ssenariy, indeks vaznlari va jarayon parametrlari. “Qo‘llash” bosilgach model qayta o‘qitiladi.':'Сценарий, веса индекса и параметры процесса. После нажатия «Применить» модель переобучается.','Ssenariy':'Сценарий','Nosozlik jiddiyligi':'Тяжесть неисправности','tasodifiy':'случайная','O‘lchash shovqini':'Шум измерений','Dinamik xavf indeksi':'Динамический индекс риска','Ogohlantirish chegarasi R*':'Порог предупреждения R*','w₁ chegaraga yaqinlik':'w₁ близость к границе','w₂ hodisagacha vaqt':'w₂ время до инцидента','w₃ anomaliya':'w₃ аномалия','w₄ o‘lchovlar izchilligi':'w₄ согласованность измерений','Jarayon parametrlari':'Параметры процесса',
'TT02 topshiriq, °C':'Уставка TT02, °C','Nam material kelimi, t/soat':'Подача влажного материала, т/ч','Shnek M01 tezligi, %':'Скорость шнека M01, %','Aralashtirgich M02 tezligi, %':'Скорость мешалки M02, %','Ikkilamchi havo klapani 1-3, %':'Клапан вторичного воздуха 1-3, %','Kirish namligi (nominal), %':'Входная влажность (номинал), %','Bunker sig‘imi, t':'Ёмкость бункера, т','Indeks ufqi, min':'Горизонт индекса, мин','Operator javob vaqti, min':'Время реакции оператора, мин','Qo‘llash':'Применить','Standart qiymatlar':'Значения по умолчанию',
'Himoya chegaralari: TT01 H/HH 1120/1180 °C, TT02 H/HH 380/400 °C, λ L/LL 1,05/0,95, LT01 L/LL 15/5 % va H/HH 85/95 %, AT02 H/HH 6/8 %. Qiymatlar taxminiy.':'Границы защиты: TT01 H/HH 1120/1180 °C, TT02 H/HH 380/400 °C, λ L/LL 1,05/0,95, LT01 L/LL 15/5 % и H/HH 85/95 %, AT02 H/HH 6/8 %. Значения ориентировочные.'
},
en:{
'☰ Boshqaruv':'☰ Controls','Quritgich aparat AI — erta ogohlantirish va hodisa tahlili':'Quritgich aparat AI — early warning and incident analysis',
'Normal ish':'Normal operation','Nam material namligi keskin oshdi':'Sharp rise in feed moisture','Birlamchi havo yetishmovchiligi (1-1 klapan / ventilyator)':'Primary air shortage (valve 1-1 / fan)','Gaz klapani 1-2 zich yopilmayapti (gaz oshib ketdi)':'Gas valve 1-2 leaks (excess gas)','TT02 harorat datchigi siljishi (past ko‘rsatmoqda)':'TT02 temperature sensor drift (reads low)','Nam material kelishi to‘xtadi (konveyer 1)':'Wet material feed stopped (conveyor 1)','Shnekli ta’minlagich 3 tiqilib qoldi':'Screw feeder 3 jammed','Bunker aralashtirgichi M02 to‘xtadi — material osilib qoldi':'Hopper mixer M02 stopped — material bridging',
'Erta ogohlantirish':'Early warning','Nam materialni quritish qurilmasi':'Wet-material drying plant','Simulyatsiya · 4 soat · 10 s':'Simulation · 4 h · 10 s','Simulyatsiya · Real-time':'Simulation · Real-time',
'Umumiy ko‘rinish':'Overview','Mnemosxema':'Mimic diagram','3D ko‘rinish':'3D view','Trendlar':'Trends','AI xabarlari va indeks':'AI messages & index','Hodisa tahlili (Review)':'Incident review','Hodisalar jurnali':'Event log','Ommaviy sinov':'Batch test','O‘z ma’lumotingiz':'Your data','Matematik model':'Mathematical model','Sozlamalar':'Settings',
'Quritish qurilmasi ›':'Drying plant ›','↻ Yangilash':'↻ Refresh','Holat turi':'Scenario','Variant':'Variant','▶ Ishga tushirish':'▶ Run','To‘liq ko‘rsatish':'Show in full','Tezlik':'Speed',
'Hodisagacha berilgan ogohlantirishlar, qurilma mnemosxemasi, AI xabarlari va xavf indeksi tarkibi.':'Warnings issued before the incident, plant mimic diagram, AI messages and the composition of the risk index.',
'AI indeksi ogohlantirishi (hodisadan oldin)':'AI index warning (before the incident)','Mavjud PLC alarmlari (hodisadan oldin)':'Existing PLC alarms (before the incident)','AI diagnostika xabari (hodisadan oldin)':'AI diagnostic message (before the incident)','Birgalikda: eng erta ogohlantirish':'Combined: earliest warning',
'Nam materialni quritish qurilmasining texnologik va avtomatlashtirish sxemasi (chizma asosida). Qiymatlar real vaqtda yangilanadi: bunker sathi, shnek, gorelka alangasi, klapanlar holati va material oqimi.':'Process and automation diagram of the wet-material drying plant. Values update in real time: hopper level, screw, burner flame, valve positions and material flow.',
'Quritish qurilmasining uch o‘lchamli ko‘rinishi — mnemosxema bilan bir xil ma’lumotlardan olinadi (gorelka, quritish barabani, bunker, konveyerlar, siklon, filtr, mo‘ri, PLC va AI xavf indeksi). Sichqoncha bilan aylantiring, g‘ildirak bilan yaqinlashtiring, uskunani bosib ma’lumot ko‘ring. Pastdagi o‘ynatish tugmasi bilan jarayonni yurgizing.':'Three-dimensional view of the drying plant, driven by the same data as the mimic diagram (burner, drying drum, hopper, conveyors, cyclone, filter, stack, PLC and the AI risk index). Rotate with the mouse, zoom with the wheel, click equipment for details.',
'Umumiy':'Overview','Konveyer':'Conveyor','Bunker':'Hopper','O‘txona':'Furnace','Baraban':'Drum','Siklon / filtr / mo‘ri':'Cyclone / filter / stack','Mahsulot':'Product','PLC xonasi':'PLC room','Yuqoridan':'Top view','Aylanish':'Orbit','⏪ Takror':'⏪ Replay','🎓 Mashq':'🎓 Training','🔇 Ovoz':'🔇 Sound','📄 PDF hisobot':'📄 PDF report',
'Bu qurilmada 3D (WebGL) ishlamadi. Mnemosxema bo‘limidan foydalaning.':'3D (WebGL) does not work on this device. Use the Mimic diagram section.',
'Haroratlar, havo/gaz nisbati, namlik, bunker sathi va dinamik xavf indeksi.':'Temperatures, air/gas ratio, moisture, hopper level and the dynamic risk index.',
'Haqiqiy qiymatlarni ham ko‘rsatish (faqat simulyatsiya)':'Also show true values (simulation only)',
'TT01 — o‘txona harorati, °C':'TT01 — furnace temperature, °C','TT02 — quritish agenti harorati, °C (nuqtali chiziqlar — modeldan kutilgan qiymat ±2σ; uzuq chiziq — haqiqiy qiymat)':'TT02 — drying agent temperature, °C (dotted — model-expected value ±2σ; dashed — true value)',
'λ — birlamchi havo / gaz nisbati (FT02 / 9,5·FT01)':'λ — primary air / gas ratio (FT02 / 9.5·FT01)','Namlik, %: AT02 mahsulot (qora), AT01 kirish (kulrang), AI bashorati (sariq uzuq)':'Moisture, %: AT02 product (black), AT01 inlet (grey), AI prediction (yellow dashed)','LT01 — bunker sathi, %':'LT01 — hopper level, %','Dinamik xavf indeksi R(t)':'Dynamic risk index R(t)','Excel’ga yuklab olish (.xlsx)':'Download as Excel (.xlsx)',
'AI xabarlari va xavf indeksi':'AI messages and risk index','Operatorga beriladigan xabarlar, qurilma holati va indeks tashkil etuvchilari.':'Operator messages, plant state and the components of the index.','AI xabarlari':'AI messages',
'Kritik':'Critical','Ogohlantirish':'Warning','Diagnostika':'Diagnostics','Holat':'Status','Ma’lumot':'Info',
'Tanlangan holat bo‘yicha avtomatik tahlil: sabab, voqealar ketma-ketligi, parametrlar o‘zgarishi, texnolog va KIP xulosasi.':'Automatic analysis of the selected scenario: cause, event sequence, parameter changes, process engineer and instrumentation conclusions.','PDF hisobot (chop etish)':'PDF report (print)',
'Tanlangan holat bo‘yicha PLC, AI va tizim voqealari vaqt tartibida. Operator har bir voqeani tasdiqlaydi (ACK).':'PLC, AI and system events for the selected scenario in time order. The operator acknowledges each event (ACK).',
'Hammasini tasdiqlash':'Acknowledge all','CSV’ga eksport':'Export to CSV','Tasdiqlarni tozalash':'Clear acknowledgements','Voqealar':'Events','tasdiqlanmagan':'unacknowledged','Hozircha voqea yo‘q.':'No events yet.','Vaqt, min':'Time, min','Daraja':'Level','Manba':'Source','Voqea':'Event','Tasdiqlash':'Acknowledge','Tasdiqlandi':'Acknowledged','Simulyatsiya':'Simulation','Zaxira himoya':'Backup protection',
'Har bir nosozlik turidan 10 tadan va 50 ta normal ish ssenariysi (joriy sozlamalar bilan).':'10 scenarios of each fault type and 50 normal-operation scenarios (with the current settings).','Barcha ssenariylar bo‘yicha sinash':'Test all scenarios','5 ta variant bo‘yicha o‘rtacha':'Average over 5 variants',
'PLC/SCADA trendini Excel (.xlsx) yoki CSV fayldan yuklang. Fayl brauzerdan tashqariga chiqmaydi.':'Load a PLC/SCADA trend from an Excel (.xlsx) or CSV file. The file never leaves the browser.','Majburiy ustunlar:':'Required columns:','. Ixtiyoriy:':'. Optional:','(klapanlar, %),':'(valves, %),','(tezlik, %) — ular bo‘lmasa tegishli izchillik tekshiruvlari o‘chiriladi.':'(speed, %) — without them the related consistency checks are disabled.',
'Diskretlik, soniya':'Sampling interval, s','Normal deb olinadigan boshlang‘ich qism, %':'Initial part treated as normal, %','Fayl (.xlsx, .csv)':'File (.xlsx, .csv)','Namuna Excel yuklab olish':'Download sample Excel','Simulyatsiyaga qaytish':'Back to simulation',
'Vaqt — daqiqa, oqim — m³/soat (gaz, havo) va t/soat (material), harorat — °C, namlik — %.':'Time — minutes, flow — m³/h (gas, air) and t/h (material), temperature — °C, moisture — %.','1. Gorelka va o‘txona':'1. Burner and furnace','2. Quritish agenti (aralashma)':'2. Drying agent (mixture)','3. Quritish va mahsulot namligi':'3. Drying and product moisture','4. Bunker va ta’minot':'4. Hopper and feeding','5. Boshqaruv va himoya (PLC)':'5. Control and protection (PLC)','6. AI: izchillik qoldiqlari':'6. AI: consistency residuals','7. Dinamik xavf indeksi':'7. Dynamic risk index','8. Taxminiy parametrlar':'8. Approximate parameters',
'Ssenariy, indeks vaznlari va jarayon parametrlari. “Qo‘llash” bosilgach model qayta o‘qitiladi.':'Scenario, index weights and process parameters. The model is retrained after pressing “Apply”.','Ssenariy':'Scenario','Nosozlik jiddiyligi':'Fault severity','tasodifiy':'random','O‘lchash shovqini':'Measurement noise','Dinamik xavf indeksi':'Dynamic risk index','Ogohlantirish chegarasi R*':'Warning threshold R*','w₁ chegaraga yaqinlik':'w₁ proximity to limit','w₂ hodisagacha vaqt':'w₂ time to incident','w₃ anomaliya':'w₃ anomaly','w₄ o‘lchovlar izchilligi':'w₄ measurement consistency','Jarayon parametrlari':'Process parameters',
'TT02 topshiriq, °C':'TT02 setpoint, °C','Nam material kelimi, t/soat':'Wet material feed, t/h','Shnek M01 tezligi, %':'Screw M01 speed, %','Aralashtirgich M02 tezligi, %':'Mixer M02 speed, %','Ikkilamchi havo klapani 1-3, %':'Secondary air valve 1-3, %','Kirish namligi (nominal), %':'Inlet moisture (nominal), %','Bunker sig‘imi, t':'Hopper capacity, t','Indeks ufqi, min':'Index horizon, min','Operator javob vaqti, min':'Operator response time, min','Qo‘llash':'Apply','Standart qiymatlar':'Default values',
'Himoya chegaralari: TT01 H/HH 1120/1180 °C, TT02 H/HH 380/400 °C, λ L/LL 1,05/0,95, LT01 L/LL 15/5 % va H/HH 85/95 %, AT02 H/HH 6/8 %. Qiymatlar taxminiy.':'Protection limits: TT01 H/HH 1120/1180 °C, TT02 H/HH 380/400 °C, λ L/LL 1.05/0.95, LT01 L/LL 15/5 % and H/HH 85/95 %, AT02 H/HH 6/8 %. Values are approximate.'
}};
if(typeof module!=='undefined')module.exports=I18N;
(function(){
if(typeof document==='undefined')return;
let LANG='uz';window.LANG=LANG;
const SKIP='#mimic,#review,#kv,#msgs,#bars,#why,#whyT,#bOut,#csvMsg,#status,.eq,#k3dCmp,#k3dTip,#k3dToast,#k3dQuiz,#k3dRep,#jTab,#jInfo,#crumb,.stat b,script,style';
const nodes=[];   // {n:textNode, uz:trimmed, pre, post}
const keys=new Set([...Object.keys(I18N.ru),...Object.keys(I18N.en)]);
function scan(){const tw=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=tw.nextNode()){const p=n.parentElement;if(!p||p.closest(SKIP))continue;const t=n.nodeValue.trim();if(t&&keys.has(t)){const m=n.nodeValue.match(/^(\s*)[\s\S]*?(\s*)$/);nodes.push({n,uz:t,pre:m[1],post:m[2]})}}}
window.tr=s=>(LANG==='uz'||!s)?s:((I18N[LANG]||{})[s]||s);
function crumb(){const c=document.getElementById('crumb');if(c&&typeof VIEWS!=='undefined'&&c.dataset.v)c.textContent=tr(VIEWS[c.dataset.v])}
function apply(l){LANG=window.LANG=l;document.documentElement.lang=l;for(const o of nodes)o.n.nodeValue=o.pre+(l==='uz'?o.uz:((I18N[l]||{})[o.uz]||o.uz))+o.post;crumb();document.title=tr('Quritgich aparat AI — erta ogohlantirish va hodisa tahlili');
  try{if(typeof cur!=='undefined'&&cur)render()}catch(e){}
  try{if(window.__journal)__journal.refresh()}catch(e){}}
const sel=document.getElementById('lang');
scan();
sel.addEventListener('change',()=>{apply(sel.value);try{localStorage.setItem('qlang',sel.value)}catch(e){}});
let saved='uz';try{saved=localStorage.getItem('qlang')||'uz'}catch(e){}
if(I18N[saved]){sel.value=saved;apply(saved)}
})();
