(function(){
const $=id=>document.getElementById(id);let rp=null,score={ok:0,n:0},aud=null,sirenT=null,snd=false,lastWarn=false,lastTrip=false,lastK=-1;
const VIEWOF={TT01HH:'yoqish',TT02HH:'baraban',LAMLL:'yoqish',LTLL:'bunker',LTHH:'bunker',AT02HH:'mahsulot',TT02TRUE:'baraban'};
const ACT={TT01HH:'Gaz berishni kamaytirish, 1-2 va 1-1 klapanlarini tekshirish',TT02HH:'Gaz klapani 1-2 ni tekshirish, ikkilamchi havoni (1-3) oshirish',LAMLL:'Birlamchi havo (1-1, ventilyator) ta’minotini tekshirish, gaz berishni kamaytirish',LTLL:'Nam material konveyeri 1 ni tekshirish, ta’minotni kamaytirish',LTHH:'Shnek 3 va bunker aralashtirgichi M02 ni tekshirish, kelimni kamaytirish',AT02HH:'Ta’minotni (M01) kamaytirish yoki TT02 topshiriqni oshirish',TT02TRUE:'TT02 datchigini mahalliy o‘lchagich bilan tekshirish (KIP chaqirish)'};
function toast(m){const t=$('k3dToast');t.textContent=m;t.style.display='block';clearTimeout(toast.h);toast.h=setTimeout(()=>t.style.display='none',3800)}
const bar=$('k3dBar');function btn(id,t,title){const b=document.createElement('button');b.id=id;b.textContent=t;if(title)b.title=title;bar.insertBefore(b,$('k3dQ'));return b}
const bR=btn('k3dRp','⏪ Takror','Hodisani sekin tezlikda qayta ko‘rsatish'),bQ=btn('k3dQz','🎓 Mashq','Operator mashqi'),bS=btn('k3dSn','🔇 Ovoz','Signalizatsiya ovozi'),bP=btn('k3dPdf','📄 PDF hisobot','Hodisa hisoboti');
function stopRp(){if(rp){clearInterval(rp);rp=null}$('k3dRep').style.display='none';bR.classList.remove('on')}
bR.onclick=()=>{if(rp){stopRp();return}if(!cur)return;const a=cur.e.a;if(a.trip<0){toast('Bu variantda PLC trip yo‘q — avval nosozlik variantini tanlang va "Ishga tushirish" ni bosing.');return}
 clearInterval(timer);timer=null;const tr=a.trip,end=tr+Math.round(25/P.dt);hover=-1;prog=Math.max(0,tr-Math.round(70/P.dt));QScene.setView(VIEWOF[EV[a.tripJ].id]||'bosh');render();bR.classList.add('on');$('k3dRep').style.display='block';
 rp=setInterval(()=>{prog++;const m=prog*P.dt;$('k3dRep').textContent='TAKROR · '+(prog<tr?'trip ga '+Math.max(0,(tr-prog)*P.dt).toFixed(0)+' min qoldi':'PLC TRIP ishladi')+' · t = '+m.toFixed(0)+' min';if(prog>=end){stopRp();return}render()},70)};
function cmp(){const el=$('k3dCmp');if(!cur||!$('v-3d').classList.contains('on'))return;const k=timeK();if(k===lastK)return;lastK=k;
 const a=cur.e.a,dt=P.dt,f=v=>v>=0?(v*dt).toFixed(0)+' min':'—',on=v=>v>=0&&k>=v;
 const rows=[['AI ogohlantirish (R ≥ chegara)',a.warn,'#f5b041'],['Oddiy PLC alarmlari',a.alarm,'#8797ab'],['AI diagnostika',a.diag,'#a58be0'],['PLC himoyasi (trip)',a.trip,'#ef5350']];
 let lead='';if(a.warn>=0&&a.trip>=0)lead='AI PLC tripidan <b>'+((a.trip-a.warn)*dt).toFixed(0)+' min</b> oldin ogohlantirdi';if(a.warn>=0&&a.alarm>=0&&a.alarm>a.warn)lead+=(lead?'<br>':'')+'Oddiy alarmdan <b>'+((a.alarm-a.warn)*dt).toFixed(0)+' min</b> oldin';else if(a.warn<0&&a.trip>=0)lead='AI ogohlantirish bermadi';
 el.innerHTML='<b>AI va oddiy PLC alarmlari</b>'+rows.map(r=>'<div><span style="color:'+(on(r[1])?r[2]:'#5f7185')+'">'+(on(r[1])?'●':'○')+' '+r[0]+'</span><i>'+f(r[1])+'</i></div>').join('')+(lead?'<p>'+lead+'</p>':'')}
function ac(){if(!aud){try{aud=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}return aud}
function beep(fr,d,v=.08){const a=ac();if(!a||!snd)return;const o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=fr;g.gain.value=v;o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+d)}
function siren(on){clearInterval(sirenT);sirenT=null;if(on&&snd){let h=0;sirenT=setInterval(()=>{beep(h++%2?620:900,.16,.07)},200)}}
bS.onclick=()=>{snd=!snd;bS.textContent=snd?'🔊 Ovoz':'🔇 Ovoz';bS.classList.toggle('on',snd);if(snd){ac()&&aud.resume();beep(660,.15)}else siren(false);lastWarn=lastTrip=false}
function soundHook(){if(!cur||!snd||!$('v-3d').classList.contains('on'))return;const k=timeK(),a=cur.e.a,t=a.trip>=0&&k>=a.trip,w=a.warn>=0&&k>=a.warn&&!t;
 if(t&&!lastTrip)siren(true);if(!t&&lastTrip)siren(false);if(w&&!lastWarn){beep(880,.12);setTimeout(()=>beep(880,.12),220)}lastWarn=w;lastTrip=t}
function quiz(){if(!cur)return;stopRp();const a=cur.e.a,id=cur.idx,cand=[];for(let k=0;k<id.R.length;k+=3)if(id.R[k]>=P.RTH&&(a.trip<0||k<a.trip)&&EV[id.sif[k]])cand.push(k);
 if(!cand.length){toast('Bu variantda xavfli holat yo‘q — nosozlik variantini tanlang va "Ishga tushirish" ni bosing.');return}
 clearInterval(timer);timer=null;const k=cand[Math.floor(Math.random()*cand.length)];hover=-1;prog=k;const j=id.sif[k],ev=EV[j];QScene.setView(VIEWOF[ev.id]||'bosh');render();
 const ids=Object.keys(ACT).filter(x=>x!==ev.id).sort(()=>Math.random()-.5).slice(0,3).concat(ev.id).sort(()=>Math.random()-.5);const tt=id.ttt[k];
 const q=$('k3dQuiz');q.innerHTML='<h3>Operator mashqi</h3><p>AI xavf indeksi <b>R = '+id.R[k].toFixed(2)+'</b> (chegara '+P.RTH.toFixed(2)+'dan yuqori). Eng yaqin hodisa: <b>'+ev.name+'</b>'+(isFinite(tt)?' (~'+tt.toFixed(0)+' min).':'.')+' Qanday harakat qilasiz?</p>'+ids.map(x=>'<button data-id="'+x+'">'+ACT[x]+'</button>').join('')+'<div id="qfb"></div>';q.style.display='block';
 q.querySelectorAll('button[data-id]').forEach(b=>b.onclick=()=>{score.n++;const ok=b.dataset.id===ev.id;if(ok)score.ok++;q.querySelectorAll('button[data-id]').forEach(x=>{x.disabled=true;if(x.dataset.id===ev.id)x.style.background='#14594f'});if(!ok)b.style.background='#7a2323';
  let m='';try{const r=aiMsgs(k).find(x=>x[0]==='w');if(r)m=String(r[1])}catch(e){}
  $('qfb').innerHTML='<p style="color:'+(ok?'#22c55e':'#ef5350')+'"><b>'+(ok?'To‘g‘ri!':'Noto‘g‘ri.')+'</b> Tizim tavsiyasi: '+ACT[ev.id]+'.</p><p style="color:#8ea0b4">'+m+'</p><button id="qnext">Keyingi savol</button> <button id="qclose">Yopish</button><small>Hisob: '+score.ok+' / '+score.n+'</small>';$('qnext').onclick=quiz;$('qclose').onclick=()=>q.style.display='none'})}
bQ.onclick=quiz;
function chart(arr,a,min,max,lines){const c=document.createElement('canvas');c.width=900;c.height=250;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,900,250);const L=44,Rr=880,T=12,B=222,n=arr.length;const X=k=>L+(Rr-L)*k/(n-1),Y=v=>B-(B-T)*(v-min)/(max-min);
 x.strokeStyle='#ccd';x.strokeRect(L,T,Rr-L,B-T);x.font='12px Arial';lines.forEach(l=>{x.strokeStyle=l.c;x.setLineDash([6,4]);x.beginPath();x.moveTo(L,Y(l.v));x.lineTo(Rr,Y(l.v));x.stroke();x.setLineDash([]);x.fillStyle=l.c;x.fillText(l.t,Rr-84,Y(l.v)-3)});
 x.strokeStyle='#0b6e6e';x.lineWidth=1.8;x.beginPath();let f=1;const stp=Math.max(1,Math.floor(n/450));for(let k=0;k<n;k+=stp){const v=arr[k];if(!isFinite(v))continue;f?(x.moveTo(X(k),Y(Math.max(min,Math.min(max,v)))),f=0):x.lineTo(X(k),Y(Math.max(min,Math.min(max,v))))}x.stroke();x.lineWidth=1;
 [[a.warn,'#f5b041','AI'],[a.alarm,'#7b8a96','PLC alarm'],[a.trip,'#c0262d','TRIP']].forEach((m,i)=>{if(m[0]<0)return;x.strokeStyle=m[1];x.setLineDash([3,3]);x.beginPath();x.moveTo(X(m[0]),T);x.lineTo(X(m[0]),B);x.stroke();x.setLineDash([]);x.fillStyle=m[1];x.fillText(m[2]+' '+(m[0]*P.dt).toFixed(0)+' min',Math.min(X(m[0])+3,Rr-120),T+12+i*13)});
 x.fillStyle='#333';x.fillText(String(min),6,B);x.fillText(String(max),6,T+10);x.fillText('0',L,B+14);x.fillText((n*P.dt).toFixed(0)+' min',Rr-46,B+14);return c.toDataURL('image/png')}
bP.onclick=()=>{if(!cur){toast('Avval simulyatsiyani ishga tushiring.');return}
 const a=cur.e.a,L=cur.e.L||{},d=cur.run.d,kind=$('kind')?$('kind').selectedOptions[0].textContent:'',fm=v=>v==null||v<0?'—':v.toFixed(1)+' min';let snap='';try{if(QScene.ok())snap=QScene.snap()}catch(e){}
 let h='<html><head><meta charset="utf-8"><title>Hodisa hisoboti</title><style>body{font:13px Arial;margin:24px;color:#111}h1{font-size:20px}h2{font-size:15px;margin:18px 0 6px;border-bottom:1px solid #999}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:4px 7px;text-align:left}img{max-width:100%}p.m{background:#f3f6f8;padding:6px 9px;border-left:3px solid #0b6e6e}@media print{@page{size:A4;margin:14mm}}</style></head><body>';
 h+='<h1>Quritgich aparat AI — erta ogohlantirish va hodisa hisoboti</h1><p>Sana: '+new Date().toLocaleString('uz')+'<br>Holat: <b>'+kind+'</b></p>';
 h+='<h2>Asosiy ko‘rsatkichlar</h2><table><tr><th>Ko‘rsatkich</th><th>Qiymat</th></tr><tr><td>Hodisa (PLC himoyasi)</td><td>'+(a.trip>=0?(a.trip*P.dt).toFixed(1)+' min — '+EV[a.tripJ].name:'yo‘q')+'</td></tr><tr><td>AI ogohlantirish — hodisadan oldin</td><td>'+fm(L.warn)+'</td></tr><tr><td>Oddiy PLC alarmlari — hodisadan oldin</td><td>'+fm(L.alarm)+'</td></tr><tr><td>AI diagnostika</td><td>'+fm(L.diag)+'</td></tr><tr><td>Birgalikda (eng erta)</td><td>'+fm(L.comb)+'</td></tr><tr><td>AI chegarasi R*</td><td>'+P.RTH.toFixed(2)+'</td></tr></table>';
 const CH=[['TT01 — o‘txona harorati, °C',d.TT01,800,1250,[{v:1120,c:'#888',t:'H 1120'},{v:1180,c:'#c0262d',t:'HH 1180'}]],['TT02 — quritish agenti harorati, °C',d.TT02,250,480,[{v:P.sp,c:'#1f9d4c',t:'SP'},{v:380,c:'#888',t:'H 380'},{v:400,c:'#c0262d',t:'HH 400'}]],['λ — havo/gaz nisbati',d.LAM,.7,1.5,[{v:1.05,c:'#888',t:'L 1,05'},{v:.95,c:'#c0262d',t:'LL 0,95'}]],['LT01 — bunker sathi, %',d.LT01,0,100,[{v:15,c:'#888',t:'L 15'},{v:5,c:'#c0262d',t:'LL 5'},{v:85,c:'#888',t:'H 85'},{v:95,c:'#c0262d',t:'HH 95'}]],['AT02 — mahsulot namligi, %',d.AT02,0,32,[{v:6,c:'#888',t:'H 6'},{v:8,c:'#c0262d',t:'HH 8'}]],['AI xavf indeksi R',cur.idx.R,0,1,[{v:P.RTH,c:'#b7791f',t:'R*'}]]];
 CH.forEach(c=>{h+='<h2>'+c[0]+'</h2><img src="'+chart(c[1],a,c[2],c[3],c[4])+'">'});
 const k=a.trip>=0?a.trip:d.TT01.length-1;let ms='';try{ms=aiMsgs(k).map(x=>'<p class="m">'+String(x[1]).replace(/</g,'&lt;')+'</p>').join('')}catch(e){}
 h+='<h2>AI xabarlari (hodisa vaqtida)</h2>'+(ms||'<p>Xabar yo‘q.</p>');if(snap)h+='<h2>3D ko‘rinish (hozirgi holat)</h2><img src="'+snap+'">';h+='</body></html>';
 const fr=document.createElement('iframe');fr.style.cssText='position:fixed;right:0;bottom:0;width:0;height:0;border:0';document.body.appendChild(fr);fr.contentDocument.open();fr.contentDocument.write(h);fr.contentDocument.close();
 setTimeout(()=>{try{fr.contentWindow.focus();fr.contentWindow.print()}catch(e){const b=new Blob([h],{type:'text/html'}),l=document.createElement('a');l.href=URL.createObjectURL(b);l.download='hisobot.html';l.click()}setTimeout(()=>fr.remove(),60000)},600);toast('Hisobot tayyor — chop etish oynasida "PDF sifatida saqlash" ni tanlang.')};
const _r=render;render=function(){_r.apply(this,arguments);try{cmp();soundHook()}catch(e){console.error(e)}};
const _s=showView;showView=function(v){_s.apply(this,arguments);if(v!=='3d'){stopRp();siren(false);lastTrip=false}};
window.__k3d={report:()=>bP.onclick(),quiz,replay:()=>bR.onclick()};
})();
(function(){const b=document.getElementById('rvPdf');if(b)b.onclick=()=>{if(window.__k3d)window.__k3d.report()}})();
